#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc

_PUID=`id -u abc`

if [ "$_PUID" != "$PUID" ]; then
  usermod -o -u "$PUID" abc
fi

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
